artifacts_roots: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Sanjay0801/datasets/raw/refs/heads/main/samsum_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion